Traceback (most recent call last):
  File "/Users/ethan/opt/miniconda3/envs/pythonbook3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/ethan/opt/miniconda3/envs/pythonbook3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ethan/opt/miniconda3/envs/pythonbook3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ethan/opt/miniconda3/envs/pythonbook3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ethan/opt/miniconda3/envs/pythonbook3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/ethan/opt/miniconda3/envs/pythonbook3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ethan/opt/miniconda3/envs/pythonbook3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
vif = pd.DataFrame()
vif['VIF'] = [variance_inflation_factor(matrix.values, i) for i in range(matrix.shape[1])]
vif['variable'] = matrix.columns
vif

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[52], line 2[0m
[1;32m      1[0m vif [38;5;241m=[39m pd[38;5;241m.[39mDataFrame()
[0;32m----> 2[0m vif[[38;5;124m'[39m[38;5;124mVIF[39m[38;5;124m'[39m] [38;5;241m=[39m [43m[[49m[43mvariance_inflation_factor[49m[43m([49m[43mmatrix[49m[38;5;241;43m.[39;49m[43mvalues[49m[43m,[49m[43m [49m[43mi[49m[43m)[49m[43m [49m[38;5;28;43;01mfor[39;49;00m[43m [49m[43mi[49m[43m [49m[38;5;129;43;01min[39;49;00m[43m [49m[38;5;28;43mrange[39;49m[43m([49m[43mmatrix[49m[38;5;241;43m.[39;49m[43mshape[49m[43m[[49m[38;5;241;43m1[39;49m[43m][49m[43m)[49m[43m][49m
[1;32m      3[0m vif[[38;5;124m'[39m[38;5;124mvariable[39m[38;5;124m'[39m] [38;5;241m=[39m matrix[38;5;241m.[39mcolumns
[1;32m      4[0m vif

Cell [0;32mIn[52], line 2[0m, in [0;36m<listcomp>[0;34m(.0)[0m
[1;32m      1[0m vif [38;5;241m=[39m pd[38;5;241m.[39mDataFrame()
[0;32m----> 2[0m vif[[38;5;124m'[39m[38;5;124mVIF[39m[38;5;124m'[39m] [38;5;241m=[39m [[43mvariance_inflation_factor[49m(matrix[38;5;241m.[39mvalues, i) [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m(matrix[38;5;241m.[39mshape[[38;5;241m1[39m])]
[1;32m      3[0m vif[[38;5;124m'[39m[38;5;124mvariable[39m[38;5;124m'[39m] [38;5;241m=[39m matrix[38;5;241m.[39mcolumns
[1;32m      4[0m vif

[0;31mNameError[0m: name 'variance_inflation_factor' is not defined

