Traceback (most recent call last):
  File "/Users/ethan/opt/miniconda3/envs/pythonbook2/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/ethan/opt/miniconda3/envs/pythonbook2/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/ethan/opt/miniconda3/envs/pythonbook2/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/ethan/opt/miniconda3/envs/pythonbook2/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/ethan/opt/miniconda3/envs/pythonbook2/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/ethan/opt/miniconda3/envs/pythonbook2/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/ethan/opt/miniconda3/envs/pythonbook2/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ethan/opt/miniconda3/envs/pythonbook2/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from myst_nb import glue
import os
import pandas as pd
from pathlib import Path

cwd = os.getcwd()
os.chdir(str(Path(cwd).parents[0]) + '/Data')

df_berkely = pd.read_csv('berkeley2.csv')


import seaborn as sns

# Plot Berkely data
berkelyplot = sns.lmplot(
    data = df_berkely,
    x = "women.apply", y = "total.admit"
    #hue = "depart.size"
)


berkelyplot.set(xlabel ="Pecentage of Female Applicants", 
                ylabel = "Admission rate (both genders)")

glue("berkely-fig", berkelyplot, display=False)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[2], line 12[0m
[1;32m      7[0m os[38;5;241m.[39mchdir([38;5;28mstr[39m(Path(cwd)[38;5;241m.[39mparents[[38;5;241m0[39m]) [38;5;241m+[39m [38;5;124m'[39m[38;5;124m/Data[39m[38;5;124m'[39m)
[1;32m      9[0m df_berkely [38;5;241m=[39m pd[38;5;241m.[39mread_csv([38;5;124m'[39m[38;5;124mberkeley2.csv[39m[38;5;124m'[39m)
[0;32m---> 12[0m [38;5;28;01mimport[39;00m [38;5;21;01mseaborn[39;00m [38;5;28;01mas[39;00m [38;5;21;01msns[39;00m
[1;32m     14[0m [38;5;66;03m# Plot Berkely data[39;00m
[1;32m     15[0m berkelyplot [38;5;241m=[39m sns[38;5;241m.[39mlmplot(
[1;32m     16[0m     data [38;5;241m=[39m df_berkely,
[1;32m     17[0m     x [38;5;241m=[39m [38;5;124m"[39m[38;5;124mwomen.apply[39m[38;5;124m"[39m, y [38;5;241m=[39m [38;5;124m"[39m[38;5;124mtotal.admit[39m[38;5;124m"[39m
[1;32m     18[0m     [38;5;66;03m#hue = "depart.size"[39;00m
[1;32m     19[0m )

[0;31mModuleNotFoundError[0m: No module named 'seaborn'
ModuleNotFoundError: No module named 'seaborn'

